# version format
version: 1.0.0.{build}

image: Visual Studio 2017

cache:
  - c:\projects\umbracoworkflow\Workflow\node_modules -> **\packages.json
  
# UMBRACO_PACKAGE_PRERELEASE_SUFFIX will only be used for Release builds
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
install:
  - set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe;C:\Ruby22\bin;%PATH%
  - cmd: npm install -g gulp-cli
  - cmd: set UMBRACO_PACKAGE_MIN_VERSION=7.7.0
  - cmd: cd BuildPackage
  - cmd: Build.bat
  
branches:
  only: 
  - master

test: off
build: off

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip
  
deploy:
  - provider: NuGet
    server:
    api_key:
      secure: 0NpBePahJSE05yOwqbFIKfbfEv83bju7OKvYpHH6FeROlps+UjZcoKk7a4ToEHOG
    skip_symbols: false      
    symbol_server:    
    artifact: /.*\.nupkg/
    on:
        branch: master
        appveyor_repo_tag: true      
    
  - provider: GitHub
    tag: v1.0.0
    release: Release 1.0.0
    description: ":)"
    force_update: true
    auth_token:
        secure: Otbl8p8qCwciDqJgSWCyN0Arfs5XS1CwiHcK+r0F6uz9Rxt4gzBFvlc3cjPV3NxR
    artifact: /.*\.zip/     
    on:
        branch: master
        appveyor_repo_tag: true     